@startuml
class AnchorObjectFactory {
    + AnchorObjectFactory(container:DiContainer)
    + Create(prefab:Object) : AnchorPresenter
}
class "IFactory`2"<T1,T2> {
}
"IFactory`2" "<UnityEngine.Object,AnchorPresenter>" <|-- AnchorObjectFactory
AnchorObjectFactory --> "_container" DiContainer
@enduml
