@startuml
class AppInstaller {
    + <<override>> InstallBindings() : void
}
MonoInstaller <|-- AppInstaller
AppInstaller --> "sessionCoordinator" AzureSessionCoordinator
AppInstaller --> "addAnchorUseCase" AddAnchorUseCase
AppInstaller --> "cloudManager" SpatialAnchorManager
AppInstaller --> "objectsCreator" ObjectsCreatorImpl
AppInstaller --> "sceneAwarnessValidator" SceneAwarnessValidator
@enduml
