@startuml
class AzureSessionCoordinator {
    + isStarted : bool = false
    + Construct(anchorsRepository:IAnchorsRepository, anchorLocator:IAnchorLocator, objectsCreator:IObjectsCreator, startAzureSession:IStartAzureSession, saveAnchor:IAnchorCreator, gameObjectEditor:GameObjectEditor) : void
    + Start() : void
}
MonoBehaviour <|-- AzureSessionCoordinator
@enduml
