@startuml
interface StartAzureSession {
    invoke() : Task
}
interface AnchorRemover {
    + deleteNativeAnchor(anchorGameObject:GameObject) : void
    + deleteCloudAnchor(anchorGameObject:GameObject) : Task
}
class AzureCloudManager {
    {static} ANCHOR_TYPE_PROP : string = "ANCHOR_TYPE"
    + AzureCloudManager(cloudManager:SpatialAnchorManager)
    + <<async>> createCloudAnchor(gameObject:GameObject, propIndex:int) : Task<AnchorCreator.Result>
    + createNativeAnchor(gameObject:GameObject) : void
    + <<async>> invoke() : Task
    + deleteNativeAnchor(anchorGameObject:GameObject) : void
    + <<async>> deleteCloudAnchor(anchorGameObject:GameObject) : Task
}
AnchorCreator <|-- AzureCloudManager
AnchorRemover <|-- AzureCloudManager
StartAzureSession <|-- AzureCloudManager
AzureCloudManager --> "_cloudManager" SpatialAnchorManager
@enduml
