@startuml
class AzureSessionCoordinator {
    + isStarted : bool = false
    + Construct(anchorsRepository:AnchorsRepository, anchorLocator:AnchorLocator, objectsCreator:ObjectCreator, startAzureSession:StartAzureSession, saveAnchor:AnchorCreator, gameObjectEditor:GameObjectEditor) : void
    + Start() : void
}
MonoBehaviour <|-- AzureSessionCoordinator
@enduml
