@startuml
interface IAnchorsRepository {
    + addAnchor(anchor:AnchorGameObject) : void
    + removeAnchor(id:string) : void
    + getAnchor(id:string) : AnchorGameObject?
    + getAnchorsIds() : List<string>
}
class AnchorGameObject <<struct>> {
    + identifier : string
}
IAnchorsRepository +-- AnchorGameObject
AnchorGameObject --> "gameObject" GameObject
@enduml
