@startuml
class RemoveAnchorUseCase {
    + RemoveAnchorUseCase(anchorsRepository:AnchorsRepository, anchorRemover:AnchorRemover, gameObjectEditor:GameObjectEditor)
    + <<async>> removeAzureAnchor(theObject:GameObject) : Task
}
@enduml
