@startuml
interface AnchorCreator {
    + createNativeAnchor(gameObject:GameObject) : void
    + createCloudAnchor(gameObject:GameObject, propIndex:int) : Task<Result>
}
class Result {
}
class Success {
    + anchorIdentifier : string <<get>>
    + Success(anchorIdentifier:string)
}
class Failure {
    + exception : Exception? <<get>>
    + Failure(exception:Exception?)
}
AnchorCreator +-- Result
Result +-- Success
Result <|-- Success
Result +-- Failure
Result <|-- Failure
class AddAnchorUseCase {
    + AddAnchorUseCase(anchorsRepository:AnchorsRepository, saveAnchor:AnchorCreator, sceneAwarnessValidator:AwarnessValidator, gameObjectEditor:GameObjectEditor)
    + <<async>> createAzureAnchor(theObject:GameObject, index:int) : Task<bool>
}
AddAnchorUseCase --> "_anchorsRepository" AnchorsRepository
AddAnchorUseCase --> "_saveAnchor" AnchorCreator
AddAnchorUseCase --> "_sceneAwarnessValidator" AwarnessValidator
AddAnchorUseCase --> "_gameObjectEditor" GameObjectEditor
class AzureAnchorsReporitory {
    + addAnchor(anchorGameObject:AnchorGameObject) : void
    + removeAnchor(id:String) : void
    + getAnchor(id:String) : AnchorGameObject?
    + getAnchorsIds() : List<string>
}
AnchorsRepository <|-- AzureAnchorsReporitory
interface AwarnessValidator {
    + validateSceneReadiness() : Task
}
class SceneAwarnessValidator {
    + Construct(cloudManager:SpatialAnchorManager) : void
    + <<async>> validateSceneReadiness() : Task
    Update() : void
}
MonoBehaviour <|-- SceneAwarnessValidator
AwarnessValidator <|-- SceneAwarnessValidator
interface IBoundsControlEditor {
    + {abstract} enableBoundsControl() : void
    + {abstract} disableBoundsControl() : void
}
interface IBoundsControlProvider {
}
class BoundsControlRepository {
    + enableBoundsControl() : void
    + disableBoundsControl() : void
}
class "IReadOnlyReactiveProperty`1"<T> {
}
IBoundsControlProvider --> "areBoundsEnabled<bool>" "IReadOnlyReactiveProperty`1"
IBoundsControlEditor <|-- BoundsControlRepository
IBoundsControlProvider <|-- BoundsControlRepository
BoundsControlRepository --> "areBoundsEnabled<bool>" "IReadOnlyReactiveProperty`1"
interface ObjectCreator {
    + {abstract} createNewMachine(machineIndex:int) : void
    + {abstract} createNewMachineWithGO(machineIndex:int) : GameObject
}
class ObjectsCreatorImpl {
    + Construct(machineViewFactory:MachineView.Factory, anchorPresenterFactory:AnchorPresenter.Factory) : void
    + createNewMachine(machineIndex:int) : void
    + createNewMachineWithGO(machineIndex:int) : GameObject
}
MonoBehaviour <|-- ObjectsCreatorImpl
ObjectCreator <|-- ObjectsCreatorImpl
class AppInstaller {
    + <<override>> InstallBindings() : void
}
MonoInstaller <|-- AppInstaller
AppInstaller --> "sessionCoordinator" AzureSessionCoordinator
AppInstaller --> "addAnchorUseCase" AddAnchorUseCase
AppInstaller --> "cloudManager" SpatialAnchorManager
AppInstaller --> "objectsCreator" ObjectsCreatorImpl
AppInstaller --> "sceneAwarnessValidator" SceneAwarnessValidator
class RemoveAnchorUseCase {
    + RemoveAnchorUseCase(anchorsRepository:AnchorsRepository, anchorRemover:AnchorRemover, gameObjectEditor:GameObjectEditor)
    + <<async>> removeAzureAnchor(theObject:GameObject) : Task
}
class DebugWindow {
}
MonoBehaviour <|-- DebugWindow
interface AnchorLocator {
    +  <<event>> CloudAnchorLocated : CloudAnchorLocated 
    + startLocatingAzureAnchors(idsToFind:string[]) : void
}
class AzureAnchorLocator {
    {static} ANCHOR_TYPE_PROP : string = "ANCHOR_TYPE"
    + AzureAnchorLocator(cloudManager:SpatialAnchorManager)
    +  <<event>> CloudAnchorLocated : CloudAnchorLocated 
    + startLocatingAzureAnchors(idsToFind:string[]) : void
}
class CloudAnchorLocatedArgs {
    + type : int <<get>>
    + identifier : string <<get>>
    + CloudAnchorLocatedArgs(pose:Pose, type:int, identifier:string)
}
AnchorLocator <|-- AzureAnchorLocator
AzureAnchorLocator --> "_cloudManager" SpatialAnchorManager
AnchorLocator +-- CloudAnchorLocatedArgs
EventArgs <|-- CloudAnchorLocatedArgs
CloudAnchorLocatedArgs --> "pose" Pose
class UserMenuView {
    + Construct(presenter:UserMenuPresenter) : void
}
MonoBehaviour <|-- UserMenuView
UserMenuView --> "enableBoundsButton" Interactable
UserMenuView --> "disableBoundsButton" Interactable
interface StartAzureSession {
    invoke() : Task
}
interface AnchorRemover {
    + deleteNativeAnchor(anchorGameObject:GameObject) : void
    + deleteCloudAnchor(anchorGameObject:GameObject) : Task
}
class AzureCloudManager {
    {static} ANCHOR_TYPE_PROP : string = "ANCHOR_TYPE"
    + AzureCloudManager(cloudManager:SpatialAnchorManager)
    + <<async>> createCloudAnchor(gameObject:GameObject, propIndex:int) : Task<AnchorCreator.Result>
    + createNativeAnchor(gameObject:GameObject) : void
    + <<async>> invoke() : Task
    + deleteNativeAnchor(anchorGameObject:GameObject) : void
    + <<async>> deleteCloudAnchor(anchorGameObject:GameObject) : Task
}
AnchorCreator <|-- AzureCloudManager
AnchorRemover <|-- AzureCloudManager
StartAzureSession <|-- AzureCloudManager
AzureCloudManager --> "_cloudManager" SpatialAnchorManager
interface GameObjectEditor {
    setName(gameObject:GameObject, name:string) : void
    getName(gameObject:GameObject) : string
    setPose(gameObject:GameObject, pose:Pose) : void
}
class GameObjectEditorImpl {
    + getName(gameObject:GameObject) : string
    + setName(gameObject:GameObject, name:string) : void
    + setPose(gameObject:GameObject, pose:Pose) : void
}
GameObjectEditor <|-- GameObjectEditorImpl
class UserMenuPresenter {
    + UserMenuPresenter(objectCreator:ObjectCreator, boundsControlEditor:IBoundsControlEditor)
    + enableBoundsControl() : void
    + disableBoundControls() : void
    + createNewMachine(index:int) : void
}
class MachineView {
    + Start() : void
    + Initialize(anchorPresenter:AnchorPresenter) : void
}
class MachineViewFactory {
    + MachineViewFactory(container:DiContainer)
    + Create(prefab:Object) : AnchorPresenter
    + Create(prefab:Object, presenter:AnchorPresenter) : MachineView
}
class Factory {
}
class "IFactory`3"<T1,T2,T3> {
}
class "PlaceholderFactory`3"<T1,T2,T3> {
}
MonoBehaviour <|-- MachineView
MachineView --> "addAnchorButton" Interactable
MachineView --> "removeAnchorButton" Interactable
MachineView --> "tapToPlaceButton" Interactable
MachineView --> "deleteButton" Interactable
"IFactory`3" "<UnityEngine.Object,AnchorPresenter,MachineView>" <|-- MachineViewFactory
MachineViewFactory --> "_container" DiContainer
MachineView +-- Factory
"PlaceholderFactory`3" "<UnityEngine.Object,AnchorPresenter,MachineView>" <|-- Factory
interface AnchorsRepository {
    + addAnchor(anchor:AnchorGameObject) : void
    + removeAnchor(id:string) : void
    + getAnchor(id:string) : AnchorGameObject?
    + getAnchorsIds() : List<string>
}
class AnchorGameObject <<struct>> {
    + identifier : string
}
AnchorsRepository +-- AnchorGameObject
AnchorGameObject --> "gameObject" GameObject
class AzureSessionCoordinator {
    + isStarted : bool = false
    + Construct(anchorsRepository:AnchorsRepository, anchorLocator:AnchorLocator, objectsCreator:ObjectCreator, startAzureSession:StartAzureSession, saveAnchor:AnchorCreator, gameObjectEditor:GameObjectEditor) : void
    + Start() : void
}
MonoBehaviour <|-- AzureSessionCoordinator
class AnchorObjectFactory {
    + AnchorObjectFactory(container:DiContainer)
    + Create(prefab:Object) : AnchorPresenter
}
class "IFactory`2"<T1,T2> {
}
"IFactory`2" "<UnityEngine.Object,AnchorPresenter>" <|-- AnchorObjectFactory
AnchorObjectFactory --> "_container" DiContainer
class AnchorPresenter {
    + AnchorPresenter(index:int, addAnchorUseCase:AddAnchorUseCase, removeAnchorUseCase:RemoveAnchorUseCase, boundsControlProvider:IBoundsControlProvider)
    +  <<event>> disableTapToPlace : Action 
    +  <<event>> deleteCurrentMachine : Action 
    + setAnchorCreatedState() : void
    + setAnchorNotCreatedState() : void
    + <<async>> setAnchor(gameObject:GameObject) : void
    + <<async>> removeAnchor(gameObject:GameObject) : void
    + delete() : void
    + setTapToPlaceNotStarted() : void
}
class "IReadOnlyReactiveProperty`1"<T> {
}
class Factory {
}
class State {
    + isAddAnchorVisible : bool = true
    + isTapToPlaceVisible : bool = true
    + isDeleteMachineVisible : bool = true
    + isRemoveAnchorVisible : bool = false
    + areBoundControlsVisible : bool = false
    + State(state:State)
}
class "PlaceholderFactory`2"<T1,T2> {
}
AnchorPresenter --> "state<State>" "IReadOnlyReactiveProperty`1"
AnchorPresenter +-- Factory
"PlaceholderFactory`2" "<int,AnchorPresenter>" <|-- Factory
AnchorPresenter +-- State
class MachinesProvider {
    Start() : void
    Update() : void
}
MonoBehaviour <|-- MachinesProvider
@enduml
