@startuml
interface IRemoveAnchorUseCase {
    + removeAzureAnchor(theObject:GameObject) : Task
}
class RemoveAnchorUseCase {
    + RemoveAnchorUseCase(anchorsRepository:IAnchorsRepository, anchorRemover:IAnchorRemover, gameObjectEditor:IGameObjectEditor)
    + <<async>> removeAzureAnchor(theObject:GameObject) : Task
}
IRemoveAnchorUseCase <|-- RemoveAnchorUseCase
@enduml
